[[plugins]]
repo = 'zchee/deoplete-jedi'
hook_add = '''
  let g:python2_host_prog = '/usr/bin/python2'
  let g:python3_host_prog = '/usr/bin/python3'
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

